jobs:
  include:
    - stage: unit test
      language: python
      catch: pip
      python:
        - "3.6"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
        - pip install .
      # command to run tests
      script: pytest
             
    - stage: release to pypi
      if: type = push
      language: python
      catch: pip
      python:
        - "3.6"
      script:
        - echo "Skipping tests"
      deploy:
        provider: pypi
        user: Addison_Gao
        password:
          secure: "a6Uw0Aoav1md6LGfdvWPnEwFQ1x/O8HawNg/wQPLtLLhLrRgMCWk1SttWtx1xl9snCgGjYuQc5ThQxUQVvTxx5vb+PlQ/hZVigXoOAd7CQYOJq3K8TiGqRNE6TSRmrWn0MSk6JDzV/Jt337i6ytSpemEUM/q5Qcn685fvNaOmzDXvhq+GvfxNyGANMiPOerEF1fKSLc4WsQEWIMvy28DnArKLbobNu7xv/BGbnsVHcPa4YUd7/foGDYFmKx7O4JKQlXfm9AvQ7655QBLmk/4QsYkq993DhAVsmHCtJo0RaeWRig/NaF2bgUDJV0DOzZsMhjd6OQIj+KIR6YAjQGWjMYl2R3rePBRyrOu/3AV23jL7HU1KBegQS92+QUavnaGF9UXHfxa9K6GJAJiOVjVjA8Ezc2ueY4EaaHuG3An7FiPmIkAb/m/Yq7Rc4yxpOzXulZI/AVWkQEar8gB/zFjOcZMYGumEBNbBySX+Di69Cvq2VfrO1AHspzSOVnUAzEaG63w2fOALj/f6jzR9ufRiNaa06ZNH/LUod1l3xrchHiCDTZdSqsSNu1Sv8zwRPvDDHtkfMPlFIMW6p4yOnMvKHDLWhjMPBsFq1NFWU9EOWbzlIomgyDHOapqfGSuj2kFPtdMSxwwoHiAdEmFeMPlvTivhr/0IrsQ9z6PDnyr8Jk="
        on:
          tags: true
      