jobs:
  include:
    - stage: unit test
      language: python
      catch: pip
      python:
        - "3.6"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
        - pip install .
      # command to run tests
      script: pytest
             
    - stage: release to pypi
      if: type = push
      language: python
      catch: pip
      python:
        - "3.6"
      script:
        - echo "Skipping tests"
      deploy:
        provider: pypi
        user: Addison_Gao
        password:
          secure: "Ch/Y0cA3YO/IUlCdPqStKqD9ciS9ITUXOuUJQIo/hIuQwnme7KUEjvNc9GvOCvweUCH2ndN5iiByro6b4H3BEQ8EVUdRPtllh72TSxqxQYTT/6XRPLHRwvBZOne8C9AaMuORBX9dH2K4amfT+Mw3iBbRqta10Vy2PwBg+lBu/RamB//NOUuH1hv/7gCYuuugLz7PFW5tWNZx+8Quv8S/HkN8DjwLqhP/h6pTVbgeLAiW3OoqSEHMnO49HC5NxwbgXb6NsEg+XZabnuVgo2Uxjn+LSAAQTYpjLa/or+w0XIukFVdZMNw7C+E+tScDYRbumuCLpeqrxDSshVQcl3YLyKdgQyyWMmvjF5ZvcXH/gG4GUtJ2OwGuR31ZeVkJP3llYcmd2t69VEAfAApE3gZO9pwMjl4ahOBht6+k5HaRYKONs4L/AKRxSfL94J86VG3OrHni1H9Fdb3wAqqC1DyZTLLdF1gUYpEqJ5CX5/3JN86w9U4IvVYPtK1bulzsAOPmbwfb8rIXwxHIvZBEQBtSeXjq7cBOwMPg8ns8Suqe1X1WVrhpYMXqFakzxKxV5sCkh1oAW+KbXdCrcuxjZb8YsnJHBqhu2e+tnkTNhI2e4/zktPgUaU1jVpFVG3+uk5Q94MSErfx2C/xWMPNBbR0n5lqQMast+5dYf3IiGj07kBY="
        on:
          tags: true
        server: https://test.pypi.org/legacy/
      